name: Check Build On PR

on:
  pull_request:
    branches: [ '*' ]
    
jobs:
  check-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.4'
          extended: true

      - name: Build
        run: hugo --minify
